language: php

sudo: false

jobs:
  include:
    - { php: 5.3, dist: precise }
    - { php: 5.4, dist: precise }
    - { php: 5.5, dist: precise }
    - php: 5.6
    - php: nightly
    - php: hhvm

matrix:
  fast_finish: true
  allow_failures:
    - php: nightly

cache:
  directories:
    - $HOME/.composer/cache

install:
  - composer install

script: phpunit -v --coverage-clover=coverage.clover

after_script:
  - if [[ "$TRAVIS_PHP_VERSION" != "nightly" ]] && [[ "$TRAVIS_PHP_VERSION" != "hhvm" ]]; then wget https://scrutinizer-ci.com/ocular.phar && php ocular.phar code-coverage:upload --format=php-clover coverage.clover; fi
